
DROP TABLE DOCUMENT;
DROP TABLE DIFFUSER;
DROP TABLE GERER;
DROP TABLE ATTRIBUER;
DROP TABLE CANAL;
DROP TABLE PROGRAMME;
DROP TABLE UTILISATEUR;
DROP TABLE JOURNAL;
DROP TABLE PROTOCOLE;
DROP TABLE CONTRACTANT;
DROP TABLE LANGUE;
DROP TABLE GENRE;
DROP TABLE ETAT;
DROP TABLE PERMISSION;

CREATE TABLE PERMISSION (
       ID_PERM INT(3) NOT NULL AUTO_INCREMENT
     , LIB_PERM CHAR(60)
)TYPE=InnoDB;

CREATE TABLE ETAT (
       ID_ETAT CHAR(2) NOT NULL
     , LIB_ETAT CHAR(10)
)TYPE=InnoDB;

CREATE TABLE GENRE (
       ID_GENRE INT NOT NULL
     , LIB_GENRE CHAR(30)
)TYPE=InnoDB;

CREATE TABLE LANGUE (
       ID_LANGUE INT NOT NULL
     , LIBEL_LANGUE CHAR(30)
)TYPE=InnoDB;

CREATE TABLE CONTRACTANT (
       ID_CONTRAT INT NOT NULL
     , NOM_CONTRAT CHAR(30)
     , ADR_CONTRAT CHAR(80)
     , DATE_CONTRAT DATE
     , ID_DOC INT
     , DUREE_CONTRAT INT
)TYPE=InnoDB;

CREATE TABLE PROTOCOLE (
       ID_PROTO INT NOT NULL AUTO_INCREMENT
     , LIB_PROTO CHAR(30)
     , DETAIL_PROTO CHAR(30)
)TYPE=InnoDB;

CREATE TABLE JOURNAL (
       ID_JOURNAL INT NOT NULL AUTO_INCREMENT
     , DATE_JOURNAL DATE
)TYPE=InnoDB;

CREATE TABLE UTILISATEUR (
       LOGIN CHAR(6) NOT NULL
     , NOM CHAR(25)
     , PREMON CHAR(25)
     , MAIL CHAR(25)
     , PWD CHAR(6)
     , PAYS CHAR(25)
)TYPE=InnoDB;

CREATE TABLE PROGRAMME (
       ID_PROG CHAR(6)
     , TITRE CHAR(30)
     , ID_ETAT CHAR(2)
     , LOGIN CHAR(6) NOT NULL
)TYPE=InnoDB;

CREATE TABLE CANAL (
       ID_CANAL CHAR(6) NOT NULL
     , NOM_CANAL CHAR(30)
     , FLUX_MAX INT
     , ID_PROTO INT NOT NULL
     , ID_JOURNAL INT NOT NULL
     , ID_ETAT CHAR(2) NOT NULL
)TYPE=InnoDB;

CREATE TABLE ATTRIBUER (
       ID_PERM INT(3) NOT NULL
     , LOGIN CHAR(6) NOT NULL
)TYPE=InnoDB;

CREATE TABLE GERER (
       ID_CANAL CHAR(6) NOT NULL
     , LOGIN CHAR(6) NOT NULL
)TYPE=InnoDB;

CREATE TABLE DIFFUSER (
       ID_PROG CHAR(6) NOT NULL
     , ID_CANAL CHAR(6) NOT NULL
     , CALAGE_TEMPOREL CHAR(10)
     , ID_JOURNAL INT NOT NULL
)TYPE=InnoDB;

CREATE TABLE DOCUMENT (
       ID_DOC INT NOT NULL
     , TITRE CHAR(30)
     , DATE_CREATION DATE
     , DUREE CHAR(10)
     , SOURCE CHAR(30)
     , COMPOSITEUR CHAR(30)
     , INTERPRETE CHAR(30)
     , ARTISTE CHAR(30)
     , LOGIN CHAR(6) NOT NULL
     , ID_CONTRAT INT NOT NULL
     , ID_LANGUE INT NOT NULL
     , ID_GENRE INT NOT NULL
     , ID_ETAT CHAR(2) NOT NULL
)TYPE=InnoDB;

ALTER TABLE PERMISSION
  ADD CONSTRAINT PK_PERMISSION
      PRIMARY KEY (ID_PERM);

ALTER TABLE ETAT
  ADD CONSTRAINT PK_ETAT
      PRIMARY KEY (ID_ETAT);

ALTER TABLE GENRE
  ADD CONSTRAINT PK_GENRE
      PRIMARY KEY (ID_GENRE);

ALTER TABLE LANGUE
  ADD CONSTRAINT PK_LANGUE
      PRIMARY KEY (ID_LANGUE);

ALTER TABLE CONTRACTANT
  ADD CONSTRAINT PK_CONTRACTANT
      PRIMARY KEY (ID_CONTRAT);

ALTER TABLE PROTOCOLE
  ADD CONSTRAINT PK_PROTOCOLE
      PRIMARY KEY (ID_PROTO);

ALTER TABLE JOURNAL
  ADD CONSTRAINT PK_JOURNAL
      PRIMARY KEY (ID_JOURNAL);

ALTER TABLE UTILISATEUR
  ADD CONSTRAINT PK_UTILISATEUR
      PRIMARY KEY (LOGIN);

ALTER TABLE PROGRAMME
  ADD CONSTRAINT PK_PROGRAMME
      PRIMARY KEY (ID_PROG);

ALTER TABLE CANAL
  ADD CONSTRAINT PK_CANAL
      PRIMARY KEY (ID_CANAL);

ALTER TABLE ATTRIBUER
  ADD CONSTRAINT PK_ATTRIBUER
      PRIMARY KEY (ID_PERM, LOGIN);

ALTER TABLE GERER
  ADD CONSTRAINT PK_GERER
      PRIMARY KEY (ID_CANAL, LOGIN);

ALTER TABLE DIFFUSER
  ADD CONSTRAINT PK_DIFFUSER
      PRIMARY KEY (ID_PROG, ID_CANAL);

ALTER TABLE DOCUMENT
  ADD CONSTRAINT PK_DOCUMENT
      PRIMARY KEY (ID_DOC);

ALTER TABLE PROGRAMME
  ADD CONSTRAINT FK_PROGRAMME_2
      FOREIGN KEY (LOGIN)
      REFERENCES UTILISATEUR (LOGIN);

ALTER TABLE PROGRAMME
  ADD CONSTRAINT FK_PROGRAMME_3
      FOREIGN KEY (ID_ETAT)
      REFERENCES ETAT (ID_ETAT);

ALTER TABLE CANAL
  ADD CONSTRAINT FK_CANAL_1
      FOREIGN KEY (ID_PROTO)
      REFERENCES PROTOCOLE (ID_PROTO);

ALTER TABLE CANAL
  ADD CONSTRAINT FK_CANAL_2
      FOREIGN KEY (ID_JOURNAL)
      REFERENCES JOURNAL (ID_JOURNAL);

ALTER TABLE CANAL
  ADD CONSTRAINT FK_CANAL_3
      FOREIGN KEY (ID_ETAT)
      REFERENCES ETAT (ID_ETAT);

ALTER TABLE ATTRIBUER
  ADD CONSTRAINT FK_ATTRIBUER_2
      FOREIGN KEY (ID_PERM)
      REFERENCES PERMISSION (ID_PERM);

ALTER TABLE ATTRIBUER
  ADD CONSTRAINT FK_ATTRIBUER_3
      FOREIGN KEY (LOGIN)
      REFERENCES UTILISATEUR (LOGIN);

ALTER TABLE GERER
  ADD CONSTRAINT FK_GERER_2
      FOREIGN KEY (LOGIN)
      REFERENCES UTILISATEUR (LOGIN);

ALTER TABLE GERER
  ADD CONSTRAINT FK_GERER_3
      FOREIGN KEY (ID_CANAL)
      REFERENCES CANAL (ID_CANAL);

ALTER TABLE DIFFUSER
  ADD CONSTRAINT FK_DIFFUSER_2
      FOREIGN KEY (ID_PROG)
      REFERENCES PROGRAMME (ID_PROG);

ALTER TABLE DIFFUSER
  ADD CONSTRAINT FK_DIFFUSER_3
      FOREIGN KEY (ID_JOURNAL)
      REFERENCES JOURNAL (ID_JOURNAL);

ALTER TABLE DIFFUSER
  ADD CONSTRAINT FK_DIFFUSER_4
      FOREIGN KEY (ID_CANAL)
      REFERENCES CANAL (ID_CANAL);

ALTER TABLE DOCUMENT
  ADD CONSTRAINT FK_DOCUMENT_6
      FOREIGN KEY (LOGIN)
      REFERENCES UTILISATEUR (LOGIN);

ALTER TABLE DOCUMENT
  ADD CONSTRAINT FK_DOCUMENT_2
      FOREIGN KEY (ID_CONTRAT)
      REFERENCES CONTRACTANT (ID_CONTRAT);

ALTER TABLE DOCUMENT
  ADD CONSTRAINT FK_DOCUMENT_3
      FOREIGN KEY (ID_LANGUE)
      REFERENCES LANGUE (ID_LANGUE);

ALTER TABLE DOCUMENT
  ADD CONSTRAINT FK_DOCUMENT_4
      FOREIGN KEY (ID_GENRE)
      REFERENCES GENRE (ID_GENRE);

ALTER TABLE DOCUMENT
  ADD CONSTRAINT FK_DOCUMENT_5
      FOREIGN KEY (ID_ETAT)
      REFERENCES ETAT (ID_ETAT);

